apiVversion: apps/v1
kind: Deployment
metadata:
   name: web-portfolio
   labels: myapp
spec:
  replicas: 2
  selectors: web-portfolio
     matchLabeles:
       app: web-portfolio
  template:
     metadata:
        labels:
         app: web-portfolio
     spec:
       containers:
          name: web-portfolio
          images: 078724664036.dkr.ecr.ap-south-1.amazonaws.com/ecr/demo-repo:${{ env.COMMIT_ID }}
