apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portfolio
  labels:
    app: web-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-portfolio
  template:
    metadata:
      labels:
        app: web-portfolio
    spec:
      containers:
        - name: web-portfolio
          image: 078724664036.dkr.ecr.ap-south-1.amazonaws.com/ecr/demo-repo:2740ded
          ports:
            - containerPort: 3000
